### ISSUE TITLE
how to obtain the API_key for the recognition service, I try to connect to the SDK service, but got ConnectionRefusedError

### ISSUE THREAD

**Issue by babyyanxi** [exadel-inc/compreface-python-sdk#12]
**Describe the bug**

**To Reproduce**
Code example.

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Additional context**

**Comment by AhmedHessuin** [comment]
@babyyanxi  how did you solve this issue?

**Comment by pospielov** [comment]
You need to install CompreFace and create a new service. CompreFace is a self-hosted service and all the data is stored on your machine. So the only way to get an API key is to create a new service locally. 
https://github.com/exadel-inc/CompreFace#getting-started-with-compreface
