### ISSUE TITLE
pip install Error: No matching distribution found for compreface-sdk

### ISSUE THREAD

**Issue by ada5588** [exadel-inc/compreface-python-sdk#8]
Hi, I am using Windows10 and I can't install compreface-sdk through pip.
The pip version was 21.1.3.
![未命名](https://user-images.githubusercontent.com/46736461/126466855-a10cdfd2-0004-45b0-9e63-d98a181c90e8.png)

Does anyone know how to make this work?

**Comment by pospielov** [comment]
Hi, we haven't released Python SDK yet. 
We are going to release it in the near future, but until release, you can just download the repository python files and add them to your project.

**Comment by ada5588** [comment]
Okay, thanks for the reply.

**Comment by pospielov** [comment]
Hi, good news! We released Python SDK, so now you can install it from pip!

**Comment by AR-Coding-126** [comment]
you released python SDK but i face error the same error mention above
@pospielov 
![sdk error](https://user-images.githubusercontent.com/100079496/234278631-91b32f8e-be65-4f2b-8531-24e7c8a02c7c.png)

**Comment by ahodkov** [comment]
Hello @AR-Coding-126, how did you install the dependency?
